✨ Create a new pom file for freeze
chains-project/maven-lockfile pull request #711
Opened 2024-04-18 13:19 UTC by yogyagamage

Fixes
- #688 
- #697 

The freeze functionality is updated such that,
    - When freeze is executed a new pom file will be created with the default name `pom.lockfile.xml`. A different name can be used with `-DpomLockfileName` 
    - The versions for the transitive dependencies will be pinned by defining them inside `dependencyManagement` instead of declaring them as direct dependencies. Scopes will also be pinned.

2024-04-19 09:16 UTC, algomaster99 requested changes
Looks good! Suggested minor changes.

2024-04-19 09:16 UTC, algomaster99 commented on maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/FreezeDependencyMojo.java
> +    private String pomLockfileName;
```suggestion
    @Parameter(defaultValue = "pom.lockfile.xml", property = "pomLockfileOutput")
    private String pomLockfileOutput;
```

Just following convention as most CLIs have the output flag to create an output file.

2024-04-19 09:16 UTC, algomaster99 commented on maven_plugin/src/test/java/it/IntegrationTestsIT.java
> +    public void freezeWithoutDepManagement(MavenExecutionResult result) throws Exception {
Can you also add an assertion to verify that the original POM is not modified?

2024-04-19 16:09 UTC, yogyagamage commented on maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/FreezeDependencyMojo.java
> +    private String pomLockfileName;
Addressed with https://github.com/chains-project/maven-lockfile/pull/711/commits/f0c778bd7d577c30a0842e04cc9d28ef913a648d

2024-04-19 16:09 UTC, yogyagamage commented on maven_plugin/src/test/java/it/IntegrationTestsIT.java
> +    public void freezeWithoutDepManagement(MavenExecutionResult result) throws Exception {
Addressed with https://github.com/chains-project/maven-lockfile/pull/711/commits/f0c778bd7d577c30a0842e04cc9d28ef913a648d

2024-04-24 08:33 UTC, merged

2024-04-24 09:06 UTC, monperrus commented
:100: